@BASE_URL = http://127.0.0.1:5000

### Index
GET {{BASE_URL}}/
User-Agent: rest-client
Content-Type: application/json

### Hello World
GET {{BASE_URL}}/hello

### Hello World with name
POST {{BASE_URL}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "your-email@example.com",
    "password": "your-password",
    "username": "your-username"
}

### articel
GET {{BASE_URL}}/articles

### articel
GET {{BASE_URL}}/auth/all

### Get Profile
GET {{BASE_URL}}/auth/profile/67b892880260c8c9a4f62dcf

### Get Article Detail
GET {{BASE_URL}}/articles/67b8c99b0244861a3abb5773
User-Agent: rest-client
Content-Type: application/json

### Edit Article (Update)
PUT {{BASE_URL}}/articles/67b8b6e6792e3aa6e5c720ad HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
  "title": "Updated Article Title",
  "content": "Updated content for the article",
  "thumbnail": null
}

### Get Articles
GET {{BASE_URL}}/articles

###
GET {{BASE_URL}}/articles/by/67b8c99a0244861a3abb5768

### Favorite an Article
POST {{BASE_URL}}/articles/67b8c99b0244861a3abb5773/favorite HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
  "user_id": "67b8c9980244861a3abb5765"
}

###

### Get Favorites by User ID
POST {{BASE_URL}}/articles/favorite HTTP/1.1
Content-Type: application/json

{
  "user_id": "67b8c9980244861a3abb5765"
}

###

### Retrieve User Favorites
POST {{BASE_URL}}/articles/favorite HTTP/1.1
Content-Type: application/json

{
  "user_id": "67b8c9980244861a3abb5765"
}

### Remove Favorite Article
DELETE {{BASE_URL}}/articles/67b8c99b0244861a3abb5773/favorite HTTP/1.1
Content-Type: application/json

{
  "user_id": "67b8c9980244861a3abb5765"
}